// <auto-generated />
namespace SqlServerPersistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _Three : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_Three));
        
        string IMigrationMetadata.Id
        {
            get { return "202004271529560__Three"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
