// <auto-generated />
namespace SqlServerPersistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _Fourteen : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_Fourteen));
        
        string IMigrationMetadata.Id
        {
            get { return "202005191518328__Fourteen"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
