// <auto-generated />
namespace SqlServerPersistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _TowentyTow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_TowentyTow));
        
        string IMigrationMetadata.Id
        {
            get { return "202006171356146__TowentyTow"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
